<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>WhatsNext</RootNamespace>
    <AssemblyName>WhatsNext</AssemblyName>
    <UseAppHost>false</UseAppHost>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.12" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="board-template.html" />
  </ItemGroup>

</Project>
