#!/usr/bin/env bash
# Report on an Immich deployment. Reports only — deployment goes through the OMV Compose
# plugin UI, because OMV regenerates the compose file and would discard anything written
# here (see IMMICH.md).
. "$(dirname "$0")/lib.sh"
load_env

head_ "OMV compose plugin"
if dpkg -l openmediavault-compose >/dev/null 2>&1; then
  ok "openmediavault-compose $(dpkg-query -W -f='${Version}' openmediavault-compose 2>/dev/null)"
else
  warn "not installed — add omv-extras, then Services -> Compose"
fi

head_ "services"
# Four, not two. A hand-written compose that omits machine-learning silently disables
# search, faces and object recognition rather than failing.
want="immich_server immich_machine_learning immich_postgres immich_redis"
running="$(docker ps --format '{{.Names}}' 2>/dev/null || true)"
for s in $want; do
  if printf '%s\n' "$running" | grep -qx "$s"; then
    ok "$s  ($(docker inspect "$s" --format '{{.Config.Image}}' 2>/dev/null))"
  else
    [ "$s" = immich_machine_learning ] &&
      bad "$s NOT running — search/faces/object recognition are silently disabled" ||
      bad "$s NOT running"
  fi
done

head_ "image pinning"
for s in immich_postgres immich_redis; do
  img="$(docker inspect "$s" --format '{{.Config.Image}}' 2>/dev/null || true)"
  [ -z "$img" ] && continue
  case "$img" in
    *@sha256:*) ok "$s pinned by digest" ;;
    *)          warn "$s is not digest-pinned ($img) — upstream pins these" ;;
  esac
done

head_ "compose file ownership"
wd="$(docker inspect immich_server --format '{{index .Config.Labels "com.docker.compose.project.working_dir"}}' 2>/dev/null || true)"
if [ -n "$wd" ]; then
  info "compose dir: $wd"
  # Note the symlink pair: docker compose wants compose.yml/.env, OMV names files after
  # the stack and links them. Follow links before concluding a file is missing.
  for f in "$wd"/*.yml "$wd"/.env; do
    [ -e "$f" ] || continue
    [ -L "$f" ] && info "$(basename "$f") -> $(readlink "$f")"
  done
  if grep -qs "auto-generated by openmediavault" "$wd"/*.yml 2>/dev/null; then
    warn "compose is OMV-generated — edit via the UI or compose.override.yml, never on disk"
  fi
  envf="$wd/.env"
  if [ -e "$envf" ]; then
    m="$(stat -Lc %a "$envf")"
    [ "$m" = 600 ] && ok ".env mode 0600" || bad ".env mode $m — it holds the DB password, chmod 600"
  fi
else
  warn "immich_server not running; cannot locate the compose directory"
fi

head_ "data location"
for s in immich_server immich_postgres; do
  docker inspect "$s" --format '{{range .Mounts}}{{if eq .Type "bind"}}  --    '"$s"': {{.Source}} -> {{.Destination}}
{{end}}{{end}}' 2>/dev/null | grep -v '^$' || true
done
# A Postgres data directory on SMB/NFS corrupts: the locking semantics are not there.
pg="$(docker inspect immich_postgres --format '{{range .Mounts}}{{if eq .Destination "/var/lib/postgresql/data"}}{{.Source}}{{end}}{{end}}' 2>/dev/null || true)"
if [ -n "$pg" ]; then
  fstype="$(stat -f -c %T "$pg" 2>/dev/null || echo unknown)"
  case "$fstype" in
    nfs*|smb*|cifs*|fuseblk) bad "postgres data is on $fstype — it will corrupt; use a local filesystem" ;;
    *) ok "postgres data on $fstype" ;;
  esac
fi

head_ "remote access"
if tailscale serve status 2>/dev/null | grep -q ":${SERVE_PORT:-2283}"; then
  ok "served over tailnet HTTPS"
else
  info "to reach Immich from a phone with no port forwarding: tailscale serve --bg ${SERVE_PORT:-2283}"
fi

head_ "backup reminder"
info "the upload directory alone is NOT a backup — albums, faces and metadata live in the DB"
info "docker exec -t immich_postgres pg_dumpall --clean --if-exists -U \"\$DB_USERNAME\" | gzip > immich-\$(date +%F).sql.gz"

finish
